### ISSUE TITLE
[BUG] Search box is present even when search is disabled

### ISSUE THREAD

**Issue by CorruptComputer** [onweru/compose#105]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [x] If and when requested, I'll link my repo to make it easier to debug.

__⚠️ NOTE:__ If the issue isn't easy to reproduce and its author(s) decline to provide reasonable accommodation to debug, the issue will be closed.

**Describe the bug**

In `config/_default/params.toml` I have the following:
```toml
# search
[search]
on = false

[search.algolia]
enable = false # if false search will default to fusejs
id = "" # Application ID
index = "" # Index name
key = "" # Search-Only API Key
```

And on my site, the search box is still shown:
![image](https://user-images.githubusercontent.com/5573038/221725002-4b6ec956-0b88-44fe-a0be-5af40916f7c5.png)

For reference, my version of params.toml and a link to the site that this corresponds to:
https://github.com/idle-wiki/Home/blob/main/config/_default/params.toml
https://idle.wiki (very much a work in progress, has almost nothing on it yet)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser: Firefox 110
