### ISSUE TITLE
[BUG] Hosting from Subdirectory Breaks many things including layouts, 404's for SVG's & index.json

### ISSUE THREAD

**Issue by erzz** [onweru/compose#69]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

Locally running `hugo server` and `http://localhost:1313/workflows/` everything runs great though I get 404's for a number of the SVG's like carly.svg and others.

After building and publishing to github pages things get really wonky appearance wise.

I am hosting via github pages and thus end up with a subdirectory as my baseURL

https://erzz.github.io/workflows/

At first almost all images, favicons etc were missing until I added the following to config.toml

```toml
RelativeURLs=true
CanonifyURLs=true
```

That fixed a lot - but when you then navigate to docs things start to get messy with layout.   e.g. https://erzz.github.io/workflows/docs/container/container-oidc.yml/

Checking out whats happening on page load then its clear that a bunch of svg's are resulting in 404

![image](https://user-images.githubusercontent.com/58994586/147923638-a25e6516-b58d-4f75-b4b2-24c49d98c3a9.png)

My build for the pages is pretty standard fair - see https://github.com/erzz/workflows/blob/main/.github/workflows/docs.yml for details.

Full config looks like:

```toml
baseURL = "https://erzz.github.io/workflows"
title = "erzz/workflows"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = ["github.com/onweru/compose"]
#theme = "compose"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

RelativeURLs=true
CanonifyURLs=true

[outputs]
  home = ["HTML", "RSS","JSON"]
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Tried various
